/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.15).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Fatura;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-08-12T19:39:06.828Z")

@Api(value = "caixa", description = "the caixa API")
@RequestMapping(value = "/v2")
public interface CaixaApi {

    @ApiOperation(value = "Adicionar nova fatura", nickname = "addFatura", notes = "", authorizations = {
        @Authorization(value = "acme_auth", scopes = {
            @AuthorizationScope(scope = "write:acme", description = "modificar dados"),
            @AuthorizationScope(scope = "read:acme", description = "ler dados")
            })
    }, tags={ "caixa", })
    @ApiResponses(value = { 
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/caixa",
        produces = { "application/xml", "application/json" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.POST)
    ResponseEntity<Void> addFatura(@ApiParam(value = "Fatura a ser adicionada" ,required=true )  @Valid @RequestBody Fatura body);


    @ApiOperation(value = "Exclui fatura", nickname = "deleteFatura", notes = "", authorizations = {
        @Authorization(value = "acme_auth", scopes = {
            @AuthorizationScope(scope = "write:acme", description = "modificar dados"),
            @AuthorizationScope(scope = "read:acme", description = "ler dados")
            })
    }, tags={ "caixa", })
    @ApiResponses(value = { 
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Fatura not found") })
    @RequestMapping(value = "/caixa/{faturaId}",
        produces = { "application/xml", "application/json" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteFatura(@ApiParam(value = "Fatura id to delete",required=true) @PathVariable("faturaId") Long faturaId,@ApiParam(value = "" ) @RequestHeader(value="api_key", required=false) String apiKey);


    @ApiOperation(value = "Fatura por ID", nickname = "getFaturaById", notes = "Returns a single pet", response = Fatura.class, authorizations = {
        @Authorization(value = "api_key")
    }, tags={ "caixa", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Fatura.class),
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Fatura not found") })
    @RequestMapping(value = "/caixa/{faturaId}",
        produces = { "application/xml", "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Fatura> getFaturaById(@ApiParam(value = "ID of pet to return",required=true) @PathVariable("faturaId") Long faturaId);


    @ApiOperation(value = "Atualiza fatura", nickname = "updateFatura", notes = "", authorizations = {
        @Authorization(value = "acme_auth", scopes = {
            @AuthorizationScope(scope = "write:acme", description = "modificar dados"),
            @AuthorizationScope(scope = "read:acme", description = "ler dados")
            })
    }, tags={ "caixa", })
    @ApiResponses(value = { 
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Fatura not found"),
        @ApiResponse(code = 405, message = "Validation exception") })
    @RequestMapping(value = "/caixa",
        produces = { "application/xml", "application/json" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.PUT)
    ResponseEntity<Void> updateFatura(@ApiParam(value = "Fatura" ,required=true )  @Valid @RequestBody Fatura body);


    @ApiOperation(value = "Atualiza fatura", nickname = "updateFaturaWithForm", notes = "", authorizations = {
        @Authorization(value = "acme_auth", scopes = {
            @AuthorizationScope(scope = "write:acme", description = "modificar dados"),
            @AuthorizationScope(scope = "read:acme", description = "ler dados")
            })
    }, tags={ "caixa", })
    @ApiResponses(value = { 
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/caixa/{faturaId}",
        produces = { "application/xml", "application/json" }, 
        consumes = { "application/x-www-form-urlencoded" },
        method = RequestMethod.POST)
    ResponseEntity<Void> updateFaturaWithForm(@ApiParam(value = "Id",required=true) @PathVariable("faturaId") Long faturaId,@ApiParam(value = "Codigo") @RequestParam(value="codigo", required=false)  String codigo);

}
